language: csharp
mono: none
dotnet: 2.1.4
install:
 - dotnet restore
 - dotnet build
script:
 - dotnet test IMAS-QOTD-API.Tests/
notifications:
  secure: "KrLDz2wYhMlJHXvG8zYLyOdXQtADRTPofrsb2Rybs3/0R8O+FQDQiDPBNxcQNsNPpvphdsiSz/iOPbUNQ8TTNO3R9qQGit/lh1k4t981FR9tiBA4rKFWviw8yFCFq/y2kcXV+WI0MNWb6QvQOfFR3Ni9hZEv425j5+p5UH2edvl6efci2KF73nMK61sTK06JP1K83r9mpX/HqEXz/aZZPwZDZ+Hk5jR8B5RFuE7HCMsyR5fCNJHtRPrYEsi7AmRQ45Prwyw2M2GBkXGMeXx7waYKbWvhbenny32LLly21VbLkISTF1Z6NXv2sLEX4wMHIgL0+at3lT03Ci8lBc0mSjUADYtTTHO2Z9GHW7qhxc3VHI67APrhK2jzX+t4TvI+Y34zKTKzFzRRWJ7JdGTqoICqmHhRs0le7uOHxnl3ssdwWyaK7X8+sParCV3OLE2dbe+ag/HgTX/YbBZlzSY7qNj28tOmGlUeus/IPwmHLqkEBHUUxXYDA49c9GwUR8cdestXHC2bggGgYSuZ5KGip/e1VAe7A1u9uLRHldAgKy/IhVraV1LqYpAt3P3WlaADmMzwI6+52xsvGAb8BFOD0jp6dEcLQ+Z9CqfxyBtb8qy1keelexs7ZXgL1/eGAnd7T4Pu4/B6Nbe8njvua+JLm33G36NHUecev80ZDOA+Usk="
