language: csharp
mono: none
dotnet: 2.1.302
install:
- dotnet restore
- dotnet build
script:
- dotnet test IMAS-QOTD-API.Tests/
notifications:
  webhooks: 
    secure: 0k6fg07mw4QS3iUHPoJSm7d0+CU5NnSnmHPcA86B9sCnec0U9kaD38oH6XIG0STcIm6+4TUo8iwjeGtRlMPtmsC07eZRkNYokeGwJQsGLwoyyqo6ZXW0NclKv/IolrgDPcQIPwCNH9fQz9b8aDzDtKlNJiSpGoQpwlLuUItbdPo0xfwQl3EUxK9XEQ1H681+kArR554QcQzRIFFBqQghLrBpHO0uykw3OKB76ObTzKVAc2O5byz1gXLqzsmh9a2VAtZkEfC3l22AanRPIfBmZOZ1/1P1PKSxa0VQ00JJ0O8HfpWGrPaVuGw6Q1H2Pci4L/92IfiQ/sMChZTp8SKInKdu3HQZYwHYAuhsTGva37WlFN8Idk8kzIMqAWqum2Z4pHZG7nCS+Zqgj4pGbDwANVHzRPo0sdZ0z1tUAT8m9h8lQjDa9MX4HsBRKh9tAvyZ6yFvk2CXsmy3nPk3rCAJMV+Wjjilw6VTcnowImGMIsn2pb4Vp0h3Ly0HjDY3+nrPNv2SBrZG9BXwCV41YkjQMDYJpB3I4C/5HdOgdeh+IjDUvG+1qJ88jKhCcOCGnHRp1i7Snqae55yRAzsoFAiGzVZQQihPMGxM++0AoG1IwDwln3xpL0lrszr57/Tnq7OjqaV3mPVeMLKEMynGzu9C0d7FEMQgSCPHSQxjH3xVD9c=